services:
  keylangdb:
    container_name: keylangdb
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'keylangdb'
      POSTGRES_USER: 'keylang'
      POSTGRES_PASSWORD: 'keylang'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./storage:/var/lib/postgresql/data
